/*
 * This is the code for the EditMemberPnl class, which is a JPanel used for editing member information.
 * It provides a form for entering and updating member details such as first name, last name, address, phone number, gender, member type, date of birth, position, and department.
 * The form also includes buttons for saving the changes and navigating back.
 * The class uses various custom GUI components and event listeners to handle user interactions and update the member information.
 */
package GUI;

import Calander.EventDateChooser;
import Calander.SelectedAction;
import Calander.SelectedDate;
import CustomGUI.Message;
import GlassPanePopup.GlassPanePopup;
import Logic.Employee;
import Logic.GymSystem;
import Logic.PersonalTrainer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import FileManager.FileManager;
import Logic.Member;
import Logic.PolytechnicStaff;
import Logic.PolytechnicStudent;
import javax.swing.JFrame;


public class EditMemberPnl extends javax.swing.JPanel {

    Message obj = new Message();
    ManageMembersPnl manageMembersPnl;
    Member mem;

    public EditMemberPnl(ManageMembersPnl manageMembersPnl) {
        initComponents();
                // Add an ActionListener to handle the "OK" button click event on the message popup
        obj.eventOK(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                GlassPanePopup.closePopupLast();
            }
        });
                // Set up the event listener for the date chooser component
        dateChooserAddMem.setTextRefernce(txtDm);
        dateChooserAddMem.addEventDateChooser(new EventDateChooser() {
            @Override
            public void dateSelected(SelectedAction action, SelectedDate date) {
                if (action.getAction() == SelectedAction.DAY_SELECTED) {
                    dateChooserAddMem.hidePopup();
                }
            }
        });
        this.manageMembersPnl = manageMembersPnl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioButtonGender = new javax.swing.ButtonGroup();
        RadioButtonMember = new javax.swing.ButtonGroup();
        dateChooserAddMem = new Calander.DateChooser();
        textField1 = new CustomGUI.TextField();
        txtFm = new CustomGUI.TextField();
        jLabel1 = new javax.swing.JLabel();
        txtPhon = new CustomGUI.TextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtLm = new CustomGUI.TextField();
        jLabel3 = new javax.swing.JLabel();
        txtAm = new CustomGUI.TextField();
        jLabel6 = new javax.swing.JLabel();
        staff = new CustomGUI.RadioButtonCustom();
        student = new CustomGUI.RadioButtonCustom();
        femaleRadioButton = new CustomGUI.RadioButtonCustom();
        maleRadioButton = new CustomGUI.RadioButtonCustom();
        addEmpBtn = new CustomGUI.Button();
        txtPositionOrMajor = new CustomGUI.TextField();
        lblPositionOrMajor = new javax.swing.JLabel();
        txtDepartmentOrTeam = new CustomGUI.TextField();
        lblDepartmenOrTeam = new javax.swing.JLabel();
        txtDm = new CustomGUI.TextField();
        jLabel9 = new javax.swing.JLabel();
        button1 = new CustomGUI.Button();
        backBtn = new CustomGUI.Button();

        dateChooserAddMem.setForeground(new java.awt.Color(68, 176, 191));

        setBackground(new java.awt.Color(42, 107, 120));

        textField1.setEditable(false);
        textField1.setBackground(new java.awt.Color(233, 189, 78));
        textField1.setForeground(new java.awt.Color(0, 0, 0));
        textField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField1.setText("Edit Member Form");
        textField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textField1.setRound(50);
        textField1.setShadowColor(new java.awt.Color(0, 0, 0));

        txtFm.setBackground(new java.awt.Color(68, 176, 191));
        txtFm.setName("memf"); // NOI18N
        txtFm.setRound(30);
        txtFm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFmActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 189, 78));
        jLabel1.setText("First Name");

        txtPhon.setBackground(new java.awt.Color(68, 176, 191));
        txtPhon.setRound(30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(233, 189, 78));
        jLabel4.setText("Phone number ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(233, 189, 78));
        jLabel2.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(233, 189, 78));
        jLabel5.setText("Gender");

        txtLm.setBackground(new java.awt.Color(68, 176, 191));
        txtLm.setRound(30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(233, 189, 78));
        jLabel3.setText("Address");

        txtAm.setBackground(new java.awt.Color(68, 176, 191));
        txtAm.setRound(30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(233, 189, 78));
        jLabel6.setText("Member Type");

        RadioButtonMember.add(staff);
        staff.setText("Staff");
        staff.setEnabled(false);
        staff.setFocusPainted(false);
        staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffActionPerformed(evt);
            }
        });

        RadioButtonMember.add(student);
        student.setText("Student");
        student.setEnabled(false);
        student.setFocusPainted(false);
        student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentActionPerformed(evt);
            }
        });

        RadioButtonGender.add(femaleRadioButton);
        femaleRadioButton.setText("Female");
        femaleRadioButton.setFocusPainted(false);
        femaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioButtonActionPerformed(evt);
            }
        });

        RadioButtonGender.add(maleRadioButton);
        maleRadioButton.setText("Male");
        maleRadioButton.setFocusPainted(false);
        maleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioButtonActionPerformed(evt);
            }
        });

        addEmpBtn.setBackground(new java.awt.Color(68, 176, 191));
        addEmpBtn.setForeground(new java.awt.Color(233, 189, 78));
        addEmpBtn.setText("Save");
        addEmpBtn.setFocusPainted(false);
        addEmpBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemBtnActionPerformed(evt);
            }
        });

        txtPositionOrMajor.setBackground(new java.awt.Color(68, 176, 191));
        txtPositionOrMajor.setRound(30);

        lblPositionOrMajor.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblPositionOrMajor.setForeground(new java.awt.Color(233, 189, 78));
        lblPositionOrMajor.setText("Position");

        txtDepartmentOrTeam.setBackground(new java.awt.Color(68, 176, 191));
        txtDepartmentOrTeam.setRound(30);

        lblDepartmenOrTeam.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblDepartmenOrTeam.setForeground(new java.awt.Color(233, 189, 78));
        lblDepartmenOrTeam.setText("Department");

        txtDm.setBackground(new java.awt.Color(68, 176, 191));
        txtDm.setRound(30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(233, 189, 78));
        jLabel9.setText("Date of birth");

        button1.setBackground(new java.awt.Color(68, 176, 191));
        button1.setForeground(new java.awt.Color(233, 189, 78));
        button1.setText("pick");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(255, 102, 102));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/log-out (2).png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setIconTextGap(8);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(112, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFm, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(txtLm, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAm, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDm, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                        .addComponent(addEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhon, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(staff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(maleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(femaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtPositionOrMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDepartmentOrTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPositionOrMajor)
                                    .addComponent(lblDepartmenOrTeam))))))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtLm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(0, 0, 0)
                        .addComponent(txtAm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(femaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(staff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(lblPositionOrMajor)
                        .addGap(0, 0, 0)
                        .addComponent(txtPositionOrMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(lblDepartmenOrTeam)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDepartmentOrTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 19, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(29, Short.MAX_VALUE))))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFmActionPerformed

    private void femaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRadioButtonActionPerformed

    private void maleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioButtonActionPerformed

    private void addMemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemBtnActionPerformed
        String gender = null;
        if (maleRadioButton.isSelected()) {
            gender = "Male";
        } else if (femaleRadioButton.isSelected()) {
            gender = "Female";
        }
        try {
            mem.setFirstName(txtFm.getText());
            mem.setLastName(txtLm.getText());
            mem.setBirthDate(txtDm.getText());
            mem.setGender(gender);
            mem.setAddress(txtAm.getText());
            mem.setPhone(txtPhon.getText());
            if (student.isSelected()) {
                ((PolytechnicStudent) mem).setMajor(txtPositionOrMajor.getText());
                ((PolytechnicStudent) mem).setTeam(txtDepartmentOrTeam.getText());
            } else if (staff.isSelected()) {
                ((PolytechnicStaff) mem).setPosition(txtPositionOrMajor.getText());
                ((PolytechnicStaff) mem).setDepartment(txtDepartmentOrTeam.getText());

            }

            manageMembersPnl.showData();
            Message obj = new Message();
            obj.jLabel1.setText("Data has been updated");
            GlassPanePopup.showPopup(obj);
            obj.eventOK(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    GlassPanePopup.closePopupLast();
                    MainFrame.body.removeAll();
                    MainFrame.body.add(manageMembersPnl);
                    MainFrame.body.repaint();
                    MainFrame.body.revalidate();
                }
            });
            FileManager.getInstance().writeMember();
        } catch (Exception e) {
            obj.jLabel1.setText("Please check your input data");
            GlassPanePopup.showPopup(obj);
        }

    }//GEN-LAST:event_addMemBtnActionPerformed

    private void studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentActionPerformed
        if (student.isSelected()) {
            lblPositionOrMajor.setText("Major");
            lblDepartmenOrTeam.setText("Sport Team");

        }
            }//GEN-LAST:event_studentActionPerformed

    private void staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffActionPerformed
        if (staff.isSelected()) {
            lblPositionOrMajor.setText("Position");
            lblDepartmenOrTeam.setText("Department");

        }
    }//GEN-LAST:event_staffActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        dateChooserAddMem.showPopup();
    }//GEN-LAST:event_button1ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        MainFrame.body.removeAll();
        manageMembersPnl.showData();
        MainFrame.body.add(manageMembersPnl);
        MainFrame.body.repaint();
        MainFrame.body.revalidate();
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup RadioButtonGender;
    private javax.swing.ButtonGroup RadioButtonMember;
    private CustomGUI.Button addEmpBtn;
    private CustomGUI.Button backBtn;
    private CustomGUI.Button button1;
    private Calander.DateChooser dateChooserAddMem;
    private CustomGUI.RadioButtonCustom femaleRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDepartmenOrTeam;
    private javax.swing.JLabel lblPositionOrMajor;
    private CustomGUI.RadioButtonCustom maleRadioButton;
    private CustomGUI.RadioButtonCustom staff;
    private CustomGUI.RadioButtonCustom student;
    private CustomGUI.TextField textField1;
    private CustomGUI.TextField txtAm;
    private CustomGUI.TextField txtDepartmentOrTeam;
    private CustomGUI.TextField txtDm;
    private CustomGUI.TextField txtFm;
    private CustomGUI.TextField txtLm;
    private CustomGUI.TextField txtPhon;
    private CustomGUI.TextField txtPositionOrMajor;
    // End of variables declaration//GEN-END:variables
    public void showData() {
        txtFm.setText(mem.getFirstName());
        txtLm.setText(mem.getLastName());
        txtAm.setText(mem.getAddress());
        txtDm.setText(mem.getBirthDate());
        txtPhon.setText(mem.getPhone());
        if (mem.getGender().equalsIgnoreCase("male")) {
            maleRadioButton.setSelected(true);
        } else {
            femaleRadioButton.setSelected(true);
        }
        if (mem instanceof PolytechnicStudent) {
            student.setSelected(true);
            txtPositionOrMajor.setText(((PolytechnicStudent) mem).getMajor());
            txtDepartmentOrTeam.setText(((PolytechnicStudent) mem).getTeam());
        } else if (mem instanceof PolytechnicStaff) {
            staff.setSelected(true);
            txtPositionOrMajor.setText(((PolytechnicStaff) mem).getPosition());
            txtDepartmentOrTeam.setText(((PolytechnicStaff) mem).getDepartment());
        }
    }
}
