/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import CustomGUI.Message;
import Logic.Employee;
import Logic.GymSystem;
import Logic.Member;
import Logic.PersonalTrainer;
import Logic.PolytechnicStaff;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alija
 */
public class ListMembersOfTrainerPnl extends javax.swing.JPanel {

    /**
     * Creates new form ListMembersOfTrainerPnl
     */
        Message obj = new Message();
        ListPersonalTrainerPnl listPersonalTrainerPnl;
        int trainerID;
    public ListMembersOfTrainerPnl(ListPersonalTrainerPnl listPersonalTrainerPnl) {
        initComponents();
        this.listPersonalTrainerPnl = listPersonalTrainerPnl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trainerMembersTable = new Table.Table();
        textField1 = new CustomGUI.TextField();
        backBtn = new CustomGUI.Button();

        setBackground(new java.awt.Color(42, 107, 120));

        trainerMembersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member ID", "Member Name", "Member Type", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        trainerMembersTable.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        trainerMembersTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        trainerMembersTable.setShowGrid(true);
        trainerMembersTable.setShowVerticalLines(false);

        textField1.setEditable(false);
        textField1.setBackground(new java.awt.Color(233, 189, 78));
        textField1.setForeground(new java.awt.Color(0, 0, 0));
        textField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField1.setText("Members List");
        textField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textField1.setRound(50);
        textField1.setShadowColor(new java.awt.Color(0, 0, 0));

        backBtn.setBackground(new java.awt.Color(255, 102, 102));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/log-out (2).png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.setFocusPainted(false);
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setIconTextGap(8);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(761, 761, 761))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trainerMembersTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(trainerMembersTable, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        if (trainerMembersTable.getColumnModel().getColumnCount() > 0) {
            trainerMembersTable.getColumnModel().getColumn(0).setResizable(false);
            trainerMembersTable.getColumnModel().getColumn(1).setResizable(false);
            trainerMembersTable.getColumnModel().getColumn(2).setResizable(false);
            trainerMembersTable.getColumnModel().getColumn(3).setResizable(false);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        MainFrame.body.removeAll();
        MainFrame.body.add(listPersonalTrainerPnl);
        MainFrame.body.repaint();
        MainFrame.body.revalidate();
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomGUI.Button backBtn;
    private CustomGUI.TextField textField1;
    private Table.Table trainerMembersTable;
    // End of variables declaration//GEN-END:variables
    public void showData() {
        DefaultTableModel model = (DefaultTableModel) trainerMembersTable.getModel();
        model.setRowCount(0);
        PersonalTrainer empFound = null;
        for (Employee emp : GymSystem.employees) {
            if (emp instanceof PersonalTrainer) {
//                String empIDString = "" + emp.getId();
                if (emp.getId() == (trainerID)) {
                    empFound = (PersonalTrainer) emp;
                    break;
                }
            }
        }
        for (Member mem : empFound.getMembers()) {
            if (mem instanceof PolytechnicStaff) {
                trainerMembersTable.addRow(new Object[]{mem.getId(), mem.getFullName(), "Polytechnic Staff", mem.getPhone()});
            } else {
                trainerMembersTable.addRow(new Object[]{mem.getId(), mem.getFullName(), "Polytechnic Student", mem.getPhone()});
            }
        }
        textField1.setText(  empFound.getFullName() + " Members List");
    }
}
