/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import CustomGUI.Message;
import GlassPanePopup.GlassPanePopup;
import Logic.Employee;
import Logic.GymSystem;
import Logic.PersonalTrainer;
import javax.swing.table.DefaultTableModel;

/**
 * This class represents a panel for listing personal trainers.
 * It displays a table of personal trainers with their information and allows the user to select a trainer to view their assigned members.
 */
public class ListPersonalTrainerPnl extends javax.swing.JPanel {

    /**
     * Creates new form ListPersonalTrainerPnl
     */
    ListMembersOfTrainerPnl listMembersOfTrainerPnl = new ListMembersOfTrainerPnl(this);
    Message obj = new Message();

    public ListPersonalTrainerPnl() {
        initComponents();
        trainersListTable.fixTable(jScrollPane3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new CustomGUI.TextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        trainersListTable = new Table.Table();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(42, 107, 120));

        textField1.setEditable(false);
        textField1.setBackground(new java.awt.Color(233, 189, 78));
        textField1.setForeground(new java.awt.Color(0, 0, 0));
        textField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField1.setText("List Perosnal trainer");
        textField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textField1.setRound(50);
        textField1.setShadowColor(new java.awt.Color(0, 0, 0));

        trainersListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trainer ID", "Trainer Name", "Phone", "NO. Members Assigned"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        trainersListTable.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        trainersListTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        trainersListTable.setShowGrid(true);
        trainersListTable.setShowVerticalLines(false);
        trainersListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                trainersListTableMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(trainersListTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 189, 78));
        jLabel1.setText("<html><center>Select a trianer to view the members</center></html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
  /**
     * Handles the event when the mouse is released on the trainersListTable.
     * If a trainer is selected, the listMembersOfTrainerPnl is shown with the selected trainer's information.
     * Otherwise, a message is displayed to prompt the user to select a trainer.
     * @param evt The MouseEvent object.
     */ 
    private void trainersListTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainersListTableMouseReleased
        if (trainersListTable.getSelectedRow() != -1) {
            MainFrame.body.removeAll();
            MainFrame.body.add(listMembersOfTrainerPnl);
            listMembersOfTrainerPnl.trainerID = (int) trainersListTable.getValueAt(trainersListTable.getSelectedRow(), 0);
            listMembersOfTrainerPnl.showData();
            MainFrame.body.repaint();
            MainFrame.body.revalidate();
        } else {
            obj.jLabel1.setText("Please Select an employee to edit");
            GlassPanePopup.showPopup(obj);
        }
    }//GEN-LAST:event_trainersListTableMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private CustomGUI.TextField textField1;
    private Table.Table trainersListTable;
    // End of variables declaration//GEN-END:variables
       // End of variables declaration                   
    /**
     * Populates the trainersListTable with personal trainers' information.
     */
    public void populateTrainersTable() {
        DefaultTableModel model = (DefaultTableModel) trainersListTable.getModel();
        model.setRowCount(0);
        for (Employee emp : GymSystem.employees) {
            if (emp instanceof PersonalTrainer) {
                trainersListTable.addRow(new Object[]{emp.getId(), emp.getFullName(), emp.getPhone(), ((PersonalTrainer) emp).getMembers().size()});
            }
        }
    }
}
